### ISSUE TITLE
Gallery don't work with repeatable fields

### ISSUE THREAD

**Issue by Art2B** [mustardBees/cmb-field-gallery#15]
Hello,

I've been trying to use Cmb field gallery within a repeatable group of fields with one gallery in each.

But there is a weird bug. All the gallery are just one. Every time I add an image inside a gallery, I get this image inside the others. When I update the one gallery, it didn't work because when I reopened it, I got the same value as the other galleries.

I there something I've missed or this plugin don't support repeateable fields

**Comment by mustardBees** [comment]
Hi @Art2B. I haven't looked at supporting repeatable field groups for this extension. [CMB2's `file_list`](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file_list) provides similar functionality and is probably the way to go.
