### ISSUE TITLE
Spining disc in Gallery Ajax 4.7n

### ISSUE THREAD

**Issue by alanef** [mustardBees/cmb-field-gallery#16]
Hi,  does this still work?

Currently on my test system ( 4.7.. ) I get the gallery opens but just a spinning disc.  Seems like an ajax call issue, but I can't see anything in the debug logs.

I also breaks  the media library. 

Shame if it doesn't as this would have been a neat solution.

**Comment by mustardBees** [comment]
I'd consider this repo deprecated. I will get around to adding a notice one day!

CMB2's native [`file_list`](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file_list) provides similar functionality; including drag and drop reordering.

@interglobalvision appear to be [maintaining a fork of this gallery project](https://github.com/interglobalvision/cmb-field-gallery). However, I have not personally tested this out.

**Comment by alanef** [comment]
Lol, you know I wasted time going round in circles - then ended up creating a 'group' in CMB2, and the its right there on my other scree in the list of types... Dooh
