### ISSUE TITLE
Show Images in Metabox

### ISSUE THREAD

**Issue by chrispiciullo** [mustardBees/cmb-field-gallery#4]
Hi mustardBees!

Just a quick question for you but is there a way to show the gallery images added in the metabox similar to the way that the default "file_list" field type works. If not, any plans for including this in the future? Thanks in advance!

**Comment by mattkrupnik** [comment]
I added thumbnail preview.
https://github.com/mustardBees/cmb-field-gallery/pull/9
Feel free to checkin changes.

Cheers.
Matt

**Comment by chrispiciullo** [comment]
Just gave this a test and it works great. Thanks, Matt!

**Comment by mustardBees** [comment]
I will test and merge shortly. Thanks @mattkrupnik for your contribution and @chrispiciullo for testing it out!

**Comment by jakebresnehan** [comment]
@mustardBees Just curious on why this hasn't been merged in yet?

**Comment by mustardBees** [comment]
Sorry for the delay on this one! I was going to put time aside to not only merge this in, but also add support for repeatable field groups.

[CMB2's `file_list`](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file_list) now provides similar functionality. I'm not sure there is value in continuing development of this field type. Any thoughts?

**Comment by SteveHoneyNZ** [comment]
@mustardBees 
First of awesome work, much appreciated.
My two cents is this still very much has value - certainly in my use case. Although the CMB2's ```file_list``` works in a very similar way the media frame it constructs means you can only add one image each time it's open (which seems an odd choice given the 'multiple' name).
The thumbnail display in CMB2 is great though
@mattkrupnik 
The thumbnail display is a great addition, however if you add images to a Galley field in a metabox that also has has an ```Image```,```Multiple Files``` or ```oEmbed``` field the Galley images are also displayed beneath these fields.
Looking at the [CMB2 JS here](https://github.com/WebDevStudios/CMB2/blob/master/js/cmb2.js#L195) it's very similar to your addition, I wonder if it would be possible to 'borrow' from that code so as to have the remove and drag to re-order functionality as in the CMB2 ```Multiple Files``` field? I tried myself but JS is not my strong suit!...
Thanks again to both of you to saving me from endless hours trying to understand WP media.frame's!

**Comment by SteveHoneyNZ** [comment]
Ignore the last comment - the multi-select for file_list field types was an issue with CMB2 that I just made a pull request to fix.
If that fix gets added then, yep, this becomes pretty much obsolete as far as I can see!
Still helped me a great deal up until now so thanks again.

**Comment by mustardBees** [comment]
@SteveHoneyNZ I've just had a play with your CMB2 work on the `file_list` field. It works great! This functionality in CMB2 effectively replaces the need for this extension. I will add a deprecated notice to this field type. @jtsternberg With the next release, I suggest removing the gallery field from CMB2's third party resources list.

**Comment by jtsternberg** [comment]
@mustardBees will do, thanks for the heads up!
